### ISSUE TITLE
Migrate to Hilt

### ISSUE THREAD

**Issue by alirezanazari** [worldsnas/DaggerSkills#3]
Hi dear Seyed Jafari ( @worldsnas )
First of all thanks for this complete and useful presentation.
I would like to contribute and migrate this source to Hilt.

If you agree please let me know and I will start to migrating and send you PR in future.

**Comment by helloseyedjafari** [comment]
Hi @alirezanazari 
I'm thrilled that you liked it.
and also very excited about your PR.
Please take it away and shoot the PR.

**Comment by alirezanazari** [comment]
Dear @worldsnas , i'm ready 
Please create hilt branch then i request PR to it.
https://github.com/alirezanazari/DaggerSkills/tree/13-migrate-to-hilt

**Comment by helloseyedjafari** [comment]
Please use branch number 13

**Comment by alirezanazari** [comment]
#4

**Comment by alirezanazari** [comment]
#4 thank you and please check this PR and let me know if there was any problem.
